/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Personal Engineering Platform API
 * The API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Article,
  CreateArticleDto
} from '.././model';

import { customInstance, convertRequestInitToAxiosConfig, convertHeaders } from '../../../lib/axios';




export type articleControllerCreateResponse201 = {
  data: Article
  status: 201
}
    
export type articleControllerCreateResponseSuccess = (articleControllerCreateResponse201) & {
  headers: Headers;
};
;

export type articleControllerCreateResponse = (articleControllerCreateResponseSuccess)

export const getArticleControllerCreateUrl = () => {


  

  return `/articles`
}

export const articleControllerCreate = async (createArticleDto: CreateArticleDto, options?: RequestInit): Promise<articleControllerCreateResponse> => {
  const headers = convertHeaders(options?.headers) || {};
  return customInstance<articleControllerCreateResponse>(
    convertRequestInitToAxiosConfig(getArticleControllerCreateUrl(), {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...headers },
      body: JSON.stringify(createArticleDto)
    })
  );
}




export const getArticleControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof articleControllerCreate>>, TError,{data: CreateArticleDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof articleControllerCreate>>, TError,{data: CreateArticleDto}, TContext> => {

const mutationKey = ['articleControllerCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof articleControllerCreate>>, {data: CreateArticleDto}> = (props) => {
          const {data} = props ?? {};

          return  articleControllerCreate(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ArticleControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof articleControllerCreate>>>
    export type ArticleControllerCreateMutationBody = CreateArticleDto
    export type ArticleControllerCreateMutationError = unknown

    export const useArticleControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof articleControllerCreate>>, TError,{data: CreateArticleDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof articleControllerCreate>>,
        TError,
        {data: CreateArticleDto},
        TContext
      > => {

      const mutationOptions = getArticleControllerCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export type articleControllerFindAllResponse200 = {
  data: Article[]
  status: 200
}
    
export type articleControllerFindAllResponseSuccess = (articleControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type articleControllerFindAllResponse = (articleControllerFindAllResponseSuccess)

export const getArticleControllerFindAllUrl = () => {


  

  return `/articles`
}

export const articleControllerFindAll = async ( options?: RequestInit): Promise<articleControllerFindAllResponse> => {
  
  return customInstance<articleControllerFindAllResponse>(
    convertRequestInitToAxiosConfig(getArticleControllerFindAllUrl(), {
      ...options,
      method: 'GET'
    })
  );
}





export const getArticleControllerFindAllQueryKey = () => {
    return [
    `/articles`
    ] as const;
    }

    
export const getArticleControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof articleControllerFindAll>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerFindAll>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getArticleControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof articleControllerFindAll>>> = ({ signal }) => articleControllerFindAll({ signal });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof articleControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ArticleControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof articleControllerFindAll>>>
export type ArticleControllerFindAllQueryError = unknown


export function useArticleControllerFindAll<TData = Awaited<ReturnType<typeof articleControllerFindAll>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof articleControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof articleControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArticleControllerFindAll<TData = Awaited<ReturnType<typeof articleControllerFindAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof articleControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof articleControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArticleControllerFindAll<TData = Awaited<ReturnType<typeof articleControllerFindAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useArticleControllerFindAll<TData = Awaited<ReturnType<typeof articleControllerFindAll>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getArticleControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type articleControllerFindDraftsResponse200 = {
  data: Article[]
  status: 200
}
    
export type articleControllerFindDraftsResponseSuccess = (articleControllerFindDraftsResponse200) & {
  headers: Headers;
};
;

export type articleControllerFindDraftsResponse = (articleControllerFindDraftsResponseSuccess)

export const getArticleControllerFindDraftsUrl = () => {


  

  return `/articles/drafts`
}

export const articleControllerFindDrafts = async ( options?: RequestInit): Promise<articleControllerFindDraftsResponse> => {
  
  return customInstance<articleControllerFindDraftsResponse>(
    convertRequestInitToAxiosConfig(getArticleControllerFindDraftsUrl(), {
      ...options,
      method: 'GET'
    })
  );
}





export const getArticleControllerFindDraftsQueryKey = () => {
    return [
    `/articles/drafts`
    ] as const;
    }

    
export const getArticleControllerFindDraftsQueryOptions = <TData = Awaited<ReturnType<typeof articleControllerFindDrafts>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerFindDrafts>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getArticleControllerFindDraftsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof articleControllerFindDrafts>>> = ({ signal }) => articleControllerFindDrafts({ signal });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof articleControllerFindDrafts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ArticleControllerFindDraftsQueryResult = NonNullable<Awaited<ReturnType<typeof articleControllerFindDrafts>>>
export type ArticleControllerFindDraftsQueryError = unknown


export function useArticleControllerFindDrafts<TData = Awaited<ReturnType<typeof articleControllerFindDrafts>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerFindDrafts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof articleControllerFindDrafts>>,
          TError,
          Awaited<ReturnType<typeof articleControllerFindDrafts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArticleControllerFindDrafts<TData = Awaited<ReturnType<typeof articleControllerFindDrafts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerFindDrafts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof articleControllerFindDrafts>>,
          TError,
          Awaited<ReturnType<typeof articleControllerFindDrafts>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArticleControllerFindDrafts<TData = Awaited<ReturnType<typeof articleControllerFindDrafts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerFindDrafts>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useArticleControllerFindDrafts<TData = Awaited<ReturnType<typeof articleControllerFindDrafts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerFindDrafts>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getArticleControllerFindDraftsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type articleControllerFindOneResponse200 = {
  data: Article
  status: 200
}
    
export type articleControllerFindOneResponseSuccess = (articleControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type articleControllerFindOneResponse = (articleControllerFindOneResponseSuccess)

export const getArticleControllerFindOneUrl = (id: string,) => {


  

  return `/articles/${id}`
}

export const articleControllerFindOne = async (id: string, options?: RequestInit): Promise<articleControllerFindOneResponse> => {
  
  return customInstance<articleControllerFindOneResponse>(
    convertRequestInitToAxiosConfig(getArticleControllerFindOneUrl(id), {
      ...options,
      method: 'GET'
    })
  );
}





export const getArticleControllerFindOneQueryKey = (id?: string,) => {
    return [
    `/articles/${id}`
    ] as const;
    }

    
export const getArticleControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof articleControllerFindOne>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerFindOne>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getArticleControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof articleControllerFindOne>>> = ({ signal }) => articleControllerFindOne(id, { signal });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof articleControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ArticleControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof articleControllerFindOne>>>
export type ArticleControllerFindOneQueryError = unknown


export function useArticleControllerFindOne<TData = Awaited<ReturnType<typeof articleControllerFindOne>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof articleControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof articleControllerFindOne>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArticleControllerFindOne<TData = Awaited<ReturnType<typeof articleControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof articleControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof articleControllerFindOne>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useArticleControllerFindOne<TData = Awaited<ReturnType<typeof articleControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerFindOne>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useArticleControllerFindOne<TData = Awaited<ReturnType<typeof articleControllerFindOne>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof articleControllerFindOne>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getArticleControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type articleControllerUpdateResponse200 = {
  data: Article
  status: 200
}
    
export type articleControllerUpdateResponseSuccess = (articleControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type articleControllerUpdateResponse = (articleControllerUpdateResponseSuccess)

export const getArticleControllerUpdateUrl = (id: string,) => {


  

  return `/articles/${id}`
}

export const articleControllerUpdate = async (id: string, options?: RequestInit): Promise<articleControllerUpdateResponse> => {
  
  return customInstance<articleControllerUpdateResponse>(
    convertRequestInitToAxiosConfig(getArticleControllerUpdateUrl(id), {
      ...options,
      method: 'PATCH'
    })
  );
}




export const getArticleControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof articleControllerUpdate>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof articleControllerUpdate>>, TError,{id: string}, TContext> => {

const mutationKey = ['articleControllerUpdate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof articleControllerUpdate>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  articleControllerUpdate(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ArticleControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof articleControllerUpdate>>>
    
    export type ArticleControllerUpdateMutationError = unknown

    export const useArticleControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof articleControllerUpdate>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof articleControllerUpdate>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getArticleControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export type articleControllerRemoveResponse200 = {
  data: Article
  status: 200
}
    
export type articleControllerRemoveResponseSuccess = (articleControllerRemoveResponse200) & {
  headers: Headers;
};
;

export type articleControllerRemoveResponse = (articleControllerRemoveResponseSuccess)

export const getArticleControllerRemoveUrl = (id: string,) => {


  

  return `/articles/${id}`
}

export const articleControllerRemove = async (id: string, options?: RequestInit): Promise<articleControllerRemoveResponse> => {
  
  return customInstance<articleControllerRemoveResponse>(
    convertRequestInitToAxiosConfig(getArticleControllerRemoveUrl(id), {
      ...options,
      method: 'DELETE'
    })
  );
}




export const getArticleControllerRemoveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof articleControllerRemove>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof articleControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['articleControllerRemove'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof articleControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  articleControllerRemove(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ArticleControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof articleControllerRemove>>>
    
    export type ArticleControllerRemoveMutationError = unknown

    export const useArticleControllerRemove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof articleControllerRemove>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof articleControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getArticleControllerRemoveMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    