/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Personal Engineering Platform API
 * The API description
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type ArticleContent = { [key: string]: unknown } | null;
