/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Personal Engineering Platform API
 * The API description
 * OpenAPI spec version: 1.0
 */
import type { ArticleContent } from './articleContent';

export interface Article {
  id: number;
  title: string;
  /** @nullable */
  content?: ArticleContent;
  published: boolean;
  createdAt?: string;
  updatedAt?: string;
}
