/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Personal Engineering Platform API
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface UpdateArticleDto {
  /** The title of the article */
  title?: string;
  /** The content of the article */
  content?: string;
  /** Publish status */
  published?: boolean;
}
