/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Personal Engineering Platform API
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface UpdateUserDto {
  /** The email of the user */
  email?: string;
  /** The password of the user */
  password?: string;
  /** The name of the user */
  name?: string;
  /** The job title of the user */
  jobTitle?: string;
  /** The location of the user */
  location?: string;
  /** The company of the user */
  company?: string;
  /** The about me of the user */
  aboutMe?: string;
}
