/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Personal Engineering Platform API
 * The API description
 * OpenAPI spec version: 1.0
 */

export interface User {
  id: number;
  email: string;
  password: string;
  name?: string;
  jobTitle?: string;
  location?: string;
  company?: string;
  aboutMe?: string;
  createdAt?: string;
  updatedAt: string;
}
